name: ktx_app
description: A modular KTX management app for managing dormitory contracts, requests, complaints and room details.
publish_to: "none"

version: 1.0.0

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5
  go_router: ^16.2.4
  intl: ^0.20.2
  cached_network_image: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true